import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { buildOutputs, checkProject, lintNames, main } from '../scripts/tokens.mjs';

const PRIMITIVES = {
  color: { $type: 'color', gray: { 100: { $value: '#f3f4f6' }, 600: { $value: '#4b5563' }, 900: { $value: '#111827' } }, white: { $value: '#ffffff' } },
  space: { $type: 'dimension', 1: { $value: '4px' }, 2: { $value: '8px' } },
  radius: { $type: 'dimension', md: { $value: '4px' } },
  font: {
    family: { $type: 'fontFamily', sans: { $value: ['Inter', 'Helvetica Neue', 'sans-serif'] } },
    weight: { $type: 'fontWeight', bold: { $value: 700 } },
  },
  duration: { $type: 'duration', 150: { $value: '150ms' } },
  easing: { $type: 'cubicBezier', standard: { $value: [0.2, 0, 0.38, 0.9] } },
  shadow: {
    $type: 'shadow',
    1: { $value: { color: 'rgba(0, 0, 0, 0.1)', offsetX: '0px', offsetY: '1px', blur: '2px', spread: '0px' } },
  },
  z: { $type: 'number', modal: { $value: 1300 } },
};

const SEMANTIC = {
  color: {
    $type: 'color',
    text: { default: { $value: '{color.gray.900}' }, muted: { $value: '{color.gray.600}' } },
    surface: { default: { $value: '{color.white}' } },
  },
  motion: { duration: { fast: { $type: 'duration', $value: '{duration.150}' } } },
  elevation: { 1: { $type: 'shadow', $value: '{shadow.1}' } },
  focus: { ring: { $type: 'border', $value: { color: '{color.gray.900}', width: '2px', style: 'solid' } } },
  type: { body: { $type: 'typography', $value: { fontFamily: '{font.family.sans}', fontSize: '16px', fontWeight: '{font.weight.bold}', lineHeight: 1.5 } } },
};

const DARK = { color: { text: { default: { $value: '{color.gray.100}' } } } };

function tmpProject(outputs, { themes = true } = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bauhaus-tokens-'));
  const write = (rel, data) => {
    fs.mkdirSync(path.dirname(path.join(root, rel)), { recursive: true });
    fs.writeFileSync(path.join(root, rel), typeof data === 'string' ? data : JSON.stringify(data));
  };
  write('tokens/primitives.tokens.json', PRIMITIVES);
  write('tokens/semantic.tokens.json', SEMANTIC);
  write('tokens/themes/dark/semantic.tokens.json', DARK);
  const config = {
    name: 'T', prefix: 'ds',
    tokens: { source: 'tokens', ...(themes ? { themes: { dark: 'tokens/themes/dark' } } : {}), outputs },
  };
  write('bauhaus.config.json', config);
  return { root, config, file: (rel) => fs.readFileSync(path.join(root, rel), 'utf8'), write };
}

const ALL = [
  { format: 'css', path: 'out/tokens.css' },
  { format: 'scss', path: 'out/tokens.scss' },
  { format: 'js', path: 'out/tokens.js' },
  { format: 'ts', path: 'out/tokens.ts' },
  { format: 'json', path: 'out/tokens.json' },
  { format: 'tailwind', path: 'out/tailwind.preset.js' },
];
const quiet = { log() {}, error() {} };
const outputOf = (outputs, p) => outputs.find((o) => o.path === p).content;

test('css: header, prefixed vars, alias var() refs, themes only override', () => {
  const { root, config } = tmpProject(ALL);
  const { outputs, errors } = buildOutputs(config, root);
  assert.deepEqual(errors, []);
  const css = outputOf(outputs, 'out/tokens.css');
  assert.match(css, /^\/\* Generated by bauhaus — do not edit \*\//);
  assert.match(css, /:root \{/);
  assert.match(css, /--ds-color-gray-600: #4b5563;/);
  assert.match(css, /--ds-color-text-muted: var\(--ds-color-gray-600\);/);
  assert.match(css, /--ds-font-family-sans: Inter, "Helvetica Neue", sans-serif;/);
  assert.match(css, /--ds-easing-standard: cubic-bezier\(0\.2, 0, 0\.38, 0\.9\);/);
  assert.match(css, /--ds-shadow-1: 0px 1px 2px 0px rgba\(0, 0, 0, 0\.1\);/);
  assert.match(css, /--ds-elevation-1: var\(--ds-shadow-1\);/);
  assert.match(css, /--ds-focus-ring: 2px solid var\(--ds-color-gray-900\);/);
  assert.match(css, /--ds-z-modal: 1300;/);
  assert.match(css, /--ds-type-body-font-size: 16px;/);
  assert.match(css, /--ds-type-body-font-weight: var\(--ds-font-weight-bold\);/);
  assert.match(css, /--ds-type-body-line-height: 1\.5;/);
  const dark = css.slice(css.indexOf('[data-theme="dark"]'));
  assert.match(dark, /--ds-color-text-default: var\(--ds-color-gray-100\);/);
  assert.doesNotMatch(dark, /--ds-color-text-muted/);
});

test('scss: $prefix vars with resolved values', () => {
  const { root, config } = tmpProject(ALL);
  const scss = outputOf(buildOutputs(config, root).outputs, 'out/tokens.scss');
  assert.match(scss, /^\/\/ Generated by bauhaus — do not edit/);
  assert.match(scss, /\$ds-color-text-muted: #4b5563;/);
  assert.match(scss, /\$ds-space-2: 8px;/);
});

test('js and ts: nested object of resolved values', () => {
  const { root, config } = tmpProject(ALL);
  const { outputs } = buildOutputs(config, root);
  const js = outputOf(outputs, 'out/tokens.js');
  assert.match(js, /^\/\/ Generated by bauhaus — do not edit/);
  assert.match(js, /export const tokens = \{/);
  const obj = JSON.parse(js.slice(js.indexOf('{'), js.lastIndexOf('}') + 1));
  assert.equal(obj.color.text.muted, '#4b5563');
  assert.equal(obj.z.modal, 1300);
  assert.equal(obj.font.weight.bold, 700);
  const ts = outputOf(outputs, 'out/tokens.ts');
  assert.match(ts, /\} as const;/);
  assert.match(ts, /export type Tokens = typeof tokens;/);
});

test('json: flat map path to resolved value', () => {
  const { root, config } = tmpProject(ALL);
  const json = JSON.parse(outputOf(buildOutputs(config, root).outputs, 'out/tokens.json'));
  assert.equal(json['color.text.muted'], '#4b5563');
  assert.equal(json['space.1'], '4px');
  assert.equal(json['easing.standard'], 'cubic-bezier(0.2, 0, 0.38, 0.9)');
  assert.deepEqual(json['type.body'].fontSize, '16px');
});

test('tailwind: preset referencing css vars', () => {
  const { root, config } = tmpProject(ALL);
  const tw = outputOf(buildOutputs(config, root).outputs, 'out/tailwind.preset.js');
  assert.match(tw, /export default \{/);
  const obj = JSON.parse(tw.slice(tw.indexOf('{'), tw.lastIndexOf('}') + 1));
  const ext = obj.theme.extend;
  assert.equal(ext.colors.text.muted, 'var(--ds-color-text-muted)');
  assert.equal(ext.spacing['1'], 'var(--ds-space-1)');
  assert.equal(ext.borderRadius.md, 'var(--ds-radius-md)');
  assert.equal(ext.fontFamily.sans, 'var(--ds-font-family-sans)');
  assert.equal(ext.transitionDuration.fast, 'var(--ds-motion-duration-fast)');
  assert.equal(ext.transitionTimingFunction.standard, 'var(--ds-easing-standard)');
  assert.equal(ext.boxShadow['1'], 'var(--ds-elevation-1)');
  assert.equal(ext.zIndex.modal, 'var(--ds-z-modal)');
});

test('tailwind: .cjs uses module.exports', () => {
  const { root, config } = tmpProject([{ format: 'tailwind', path: 'tw.cjs' }]);
  assert.match(outputOf(buildOutputs(config, root).outputs, 'tw.cjs'), /^\/\/ Generated by bauhaus — do not edit\nmodule\.exports = \{/);
});

test('build writes files, check passes then detects drift', () => {
  const { root, file, write } = tmpProject(ALL);
  const cfg = path.join(root, 'bauhaus.config.json');
  assert.equal(main(['check', '--config', cfg], quiet), 1, 'missing outputs count as drift');
  assert.equal(main(['build', '--config', cfg], quiet), 0);
  assert.match(file('out/tokens.css'), /--ds-space-1: 4px;/);
  assert.equal(main(['check', '--config', cfg], quiet), 0);
  write('out/tokens.css', file('out/tokens.css') + '/* hand edit */\n');
  const lines = [];
  assert.equal(main(['check', '--config', cfg], { log: (m) => lines.push(m), error: (m) => lines.push(m) }), 1);
  assert.ok(lines.join('\n').includes('out/tokens.css'));
  assert.ok(!lines.join('\n').includes('out/tokens.scss'));
});

test('check fails on a dangling alias, build refuses', () => {
  const { root, write } = tmpProject(ALL);
  write('tokens/semantic.tokens.json', { color: { $type: 'color', text: { x: { $value: '{color.nope}' } } } });
  const cfg = path.join(root, 'bauhaus.config.json');
  assert.equal(main(['check', '--config', cfg], quiet), 1);
  assert.equal(main(['build', '--config', cfg], quiet), 1);
});

test('a theme that overrides an unknown token is an error', () => {
  const { root, config, write } = tmpProject(ALL);
  write('tokens/themes/dark/semantic.tokens.json', { color: { text: { ghost: { $type: 'color', $value: '#000' } } } });
  assert.match(buildOutputs(config, root).errors.join('\n'), /ghost/);
});

test('usage errors exit 2', () => {
  assert.equal(main([], quiet), 2);
  assert.equal(main(['nope'], quiet), 2);
  assert.equal(main(['build', '--config', '/no/such/file.json'], quiet), 2);
});

test('lintNames: semantic tier rules', () => {
  const tok = (p, v, extra = {}) => ({ path: p, $value: v, aliasOf: /^\{.*\}$/.test(v) ? v.slice(1, -1) : null, ...extra });
  const warnings = lintNames([
    tok('color.gray.600', '#4b5563'),
    tok('color.text.muted', '{color.gray.600}'),
    tok('color.text.blue-light', '{color.gray.600}'),
    tok('color.accent.dark', '{color.gray.600}'),
    tok('space.13px', '4px'),
    tok('semantic.text.raw', '#fff'),
    tok('component.button.radius', '4px'),
    tok('duration.150', '150ms'),
  ]).map((w) => w.split(':')[0]);
  assert.deepEqual(warnings.sort(), ['color.accent.dark', 'color.text.blue-light', 'component.button.radius', 'semantic.text.raw', 'space.13px']);
});

test('checkProject returns drifted files and warnings', () => {
  const { root, config } = tmpProject(ALL);
  const { drift, errors } = checkProject(config, root);
  assert.deepEqual(errors, []);
  assert.equal(drift.length, 6);
});

// ---------- defaultTheme: sibling themes ----------

const PALETTE = { palette: { $type: 'color', gray: { 100: { $value: '#f3f4f6' }, 900: { $value: '#111827' } } } };
const COLORS = { colors: { $type: 'color', neutral: { 100: { $value: '{palette.gray.100}' }, 900: { $value: '{palette.gray.900}' } } } };
const role = (fg, bg) => ({ text: { $type: 'color', default: { $value: `{colors.neutral.${fg}}` } }, surface: { $type: 'color', default: { $value: `{colors.neutral.${bg}}` } } });

function siblingProject({ light = role(900, 100), dark = role(100, 900), defaultTheme = 'light', outputs = ALL } = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bauhaus-sibling-'));
  const write = (rel, data) => {
    fs.mkdirSync(path.dirname(path.join(root, rel)), { recursive: true });
    fs.writeFileSync(path.join(root, rel), JSON.stringify(data));
  };
  write('tokens/palette.tokens.json', PALETTE);
  write('tokens/colors.tokens.json', COLORS);
  write('tokens/space.tokens.json', { space: { $type: 'dimension', 1: { $value: '4px' } } });
  write('tokens/themes/light/light.tokens.json', light);
  write('tokens/themes/dark/dark.tokens.json', dark);
  const config = {
    name: 'T', prefix: 'ds',
    tokens: { source: 'tokens', themes: { light: 'tokens/themes/light', dark: 'tokens/themes/dark' }, ...(defaultTheme ? { defaultTheme } : {}), outputs },
  };
  write('bauhaus.config.json', config);
  return { root, config, write };
}

test('defaultTheme: default roles land in :root and every theme gets its own block', () => {
  const { root, config } = siblingProject();
  const { outputs, errors } = buildOutputs(config, root);
  assert.deepEqual(errors, []);
  const css = outputOf(outputs, 'out/tokens.css');
  const rootBlock = css.slice(css.indexOf(':root'), css.indexOf('[data-theme="light"]'));
  assert.match(rootBlock, /--ds-palette-gray-900: #111827;/);
  assert.match(rootBlock, /--ds-colors-neutral-900: var\(--ds-palette-gray-900\);/);
  assert.match(rootBlock, /--ds-text-default: var\(--ds-colors-neutral-900\);/);
  assert.match(rootBlock, /--ds-surface-default: var\(--ds-colors-neutral-100\);/);
  const light = css.slice(css.indexOf('[data-theme="light"]'), css.indexOf('[data-theme="dark"]'));
  assert.match(light, /--ds-text-default: var\(--ds-colors-neutral-900\);/);
  assert.doesNotMatch(light, /--ds-palette/, 'themes hold roles only');
  const dark = css.slice(css.indexOf('[data-theme="dark"]'));
  assert.match(dark, /--ds-text-default: var\(--ds-colors-neutral-100\);/);
  assert.match(dark, /--ds-surface-default: var\(--ds-colors-neutral-900\);/);
});

test('defaultTheme: js, ts, json, scss and tailwind use the default theme values', () => {
  const { root, config } = siblingProject();
  const { outputs } = buildOutputs(config, root);
  assert.equal(JSON.parse(outputOf(outputs, 'out/tokens.json'))['text.default'], '#111827');
  assert.match(outputOf(outputs, 'out/tokens.scss'), /\$ds-text-default: #111827;/);
  const js = outputOf(outputs, 'out/tokens.js');
  assert.equal(JSON.parse(js.slice(js.indexOf('{'), js.lastIndexOf('}') + 1)).surface.default, '#f3f4f6');
});

test('defaultTheme: dark as default swaps :root', () => {
  const { root, config } = siblingProject({ defaultTheme: 'dark' });
  const css = outputOf(buildOutputs(config, root).outputs, 'out/tokens.css');
  assert.match(css.slice(0, css.indexOf('[data-theme')), /--ds-text-default: var\(--ds-colors-neutral-100\);/);
});

test('defaultTheme must be a key of tokens.themes', () => {
  const { root, config } = siblingProject({ defaultTheme: 'sepia' });
  assert.match(buildOutputs(config, root).errors.join('\n'), /defaultTheme "sepia" is not a theme \(light, dark\)/);
});

test('parity: a role missing from a theme is an error', () => {
  const { root, config } = siblingProject({ dark: { text: role(100, 900).text } });
  const errors = buildOutputs(config, root).errors;
  assert.deepEqual(errors, ['theme dark: missing role surface.default (defined in light)']);
  assert.equal(main(['check', '--config', path.join(root, 'bauhaus.config.json')], quiet), 1);
});

test('parity: an extra role in a theme is an error', () => {
  const dark = { ...role(100, 900), border: { $type: 'color', default: { $value: '{colors.neutral.900}' } } };
  const { root, config } = siblingProject({ dark });
  assert.deepEqual(buildOutputs(config, root).errors, ['theme dark: extra role border.default (not in light)']);
});

test('parity: also holds when the default theme has the gap', () => {
  const { root, config } = siblingProject({ light: { text: role(900, 100).text } });
  assert.deepEqual(buildOutputs(config, root).errors, ['theme dark: extra role surface.default (not in light)']);
});

test('check warns when a theme role aliases the palette directly', () => {
  const dark = { ...role(100, 900), text: { $type: 'color', default: { $value: '{palette.gray.100}' } } };
  const { root, config } = siblingProject({ dark });
  const { errors, warnings } = checkProject(config, root);
  assert.deepEqual(errors, []);
  assert.deepEqual(warnings, ['theme dark: role text.default aliases the palette directly; alias colors.* instead']);
});

test('no defaultTheme: themes stay overrides of the base (backward compatible)', () => {
  const { root, config } = siblingProject({ defaultTheme: null });
  const errors = buildOutputs(config, root).errors;
  assert.ok(errors.length && errors.every((e) => /overrides unknown token/.test(e)), errors.join('\n'));
});
