#!/usr/bin/env node
// tokens.mjs build|check [--config bauhaus.config.json]
// Builds DTCG tokens into css, scss, js, ts, json and a Tailwind preset.
import fs from 'node:fs';
import path from 'node:path';
import { parseArgs } from 'node:util';
import { fileURLToPath } from 'node:url';
import {
  deepMerge, dimensionString, durationString, flatten, loadTree, resolveTokens, substituteAliases, validateTokens,
} from './lib/dtcg.mjs';
import { FONT_GROUP, GENERIC_FAMILIES, TEXT_GROUP, TYPEFACE_GROUP, ROLES, catalogIds, lastFamily } from './lib/typography.mjs';

const HEADER = 'Generated by bauhaus — do not edit';
const FORMATS = ['css', 'scss', 'js', 'ts', 'json', 'tailwind'];
const isObj = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);
const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const TYPOGRAPHY_PARTS = { fontFamily: 'fontFamily', fontSize: 'dimension', fontWeight: 'fontWeight', lineHeight: 'number', letterSpacing: 'dimension' };

// ---------- value formatting ----------

const quoteFamily = (name) => (/^[\w-]+$/.test(name) ? name : `"${name}"`);
const formatFamily = (v) => (Array.isArray(v) ? v.map(quoteFamily).join(', ') : v);

function shadowLayer(l) {
  const parts = [l.inset ? 'inset' : '', ...[l.offsetX, l.offsetY, l.blur, l.spread ?? '0px'].map(dimensionString), formatValue('color', l.color)];
  return parts.filter(Boolean).join(' ');
}

function formatColor(v) {
  if (typeof v === 'string') return v;
  if (v.hex) return v.hex;
  const alpha = v.alpha !== undefined && v.alpha !== 1 ? ` / ${v.alpha}` : '';
  return `color(${v.colorSpace} ${v.components.join(' ')}${alpha})`;
}

/** Turn a resolved (or var()-substituted) DTCG value into a CSS string. */
export function formatValue(type, v) {
  if (typeof v === 'string' && v.startsWith('var(')) return v;
  const f = (t, x) => formatValue(t, x);
  switch (type) {
    case 'color': return formatColor(v);
    case 'dimension': return dimensionString(v);
    case 'duration': return durationString(v);
    case 'fontFamily': return formatFamily(v);
    case 'cubicBezier': return typeof v === 'string' ? v : `cubic-bezier(${v.join(', ')})`;
    case 'strokeStyle': return typeof v === 'string' ? v : 'dashed';
    case 'border': return [f('dimension', v.width), f('strokeStyle', v.style), f('color', v.color)].join(' ');
    case 'transition': return [f('duration', v.duration), f('cubicBezier', v.timingFunction), v.delay && f('duration', v.delay)].filter(Boolean).join(' ');
    case 'shadow': return (Array.isArray(v) ? v : [v]).map(shadowLayer).join(', ');
    case 'gradient': return `linear-gradient(${v.map((s) => `${f('color', s.color)} ${s.position * 100}%`).join(', ')})`;
    default: return String(v);
  }
}

const typographyParts = (value) =>
  Object.fromEntries(Object.entries(value).map(([k, v]) => [k, formatValue(TYPOGRAPHY_PARTS[k], v)]));

/** [suffix, css string] pairs for one token value. Typography splits into sub-properties. */
function entriesOf(type, value) {
  if (type === 'typography') return Object.entries(typographyParts(value)).map(([k, v]) => [`-${kebab(k)}`, v]);
  return [['', formatValue(type, value)]];
}

// ---------- css / scss ----------

const cssName = (prefix, p) => `--${prefix}-${p.replaceAll('.', '-')}`;
const scssName = (prefix, p) => `$${prefix}-${p.replaceAll('.', '-')}`;

/** Declarations for one token in CSS: aliases stay as var() references. */
function cssDeclarations(token, prefix) {
  const name = cssName(prefix, token.path);
  if (token.$type === 'typography' && token.aliasOf) {
    const target = cssName(prefix, token.aliasOf);
    return Object.keys(token.resolved).map((k) => [`${name}-${kebab(k)}`, `var(${target}-${kebab(k)})`]);
  }
  const value = substituteAliases(token.$value, (ref) => `var(${cssName(prefix, ref)})`);
  return entriesOf(token.$type, value).map(([suffix, v]) => [name + suffix, v]);
}

const block = (selector, tokens, prefix) => {
  const lines = tokens.flatMap((t) => cssDeclarations(t, prefix)).map(([n, v]) => `  ${n}: ${v};`);
  return `${selector} {\n${lines.join('\n')}\n}\n`;
};

export function renderCss(model, prefix) {
  const parts = [block(':root', model.tokens, prefix)];
  for (const theme of model.themes) parts.push(block(`[data-theme="${theme.name}"]`, theme.tokens, prefix));
  return `/* ${HEADER} */\n${parts.join('\n')}`;
}

export function renderScss(model, prefix) {
  const lines = model.tokens.flatMap((t) =>
    entriesOf(t.$type, t.resolved).map(([suffix, v]) => `${scssName(prefix, t.path)}${suffix}: ${v};`));
  return `// ${HEADER}\n${lines.join('\n')}\n`;
}

// ---------- js / ts / json / tailwind ----------

/** A leaf for js/json: numbers stay numbers, typography becomes an object of strings. */
function leafValue(token) {
  if (token.$type === 'typography') return typographyParts(token.resolved);
  if (token.$type === 'number' || (token.$type === 'fontWeight' && typeof token.resolved === 'number')) return token.resolved;
  return formatValue(token.$type, token.resolved);
}

/** Build a nested object. When a name is both a leaf and a group, the leaf moves to `DEFAULT`. */
function nest(pairs) {
  const root = {};
  for (const [segments, value] of pairs) setDeep(root, segments, value);
  return root;
}

function setDeep(obj, [head, ...rest], value) {
  if (rest.length === 0) {
    obj[head] = isObj(obj[head]) ? { ...obj[head], DEFAULT: value } : value;
    return;
  }
  if (obj[head] !== undefined && !isObj(obj[head])) obj[head] = { DEFAULT: obj[head] };
  obj[head] ??= {};
  setDeep(obj[head], rest, value);
}

const nestedTokens = (model) => nest(model.tokens.map((t) => [t.path.split('.'), leafValue(t)]));

export function renderJs(model, { ts = false } = {}) {
  const body = JSON.stringify(nestedTokens(model), null, 2);
  const tail = ts ? ' as const;\n\nexport type Tokens = typeof tokens;\n' : ';\n';
  return `// ${HEADER}\nexport const tokens = ${body}${tail}`;
}

export function renderJson(model) {
  return `${JSON.stringify(Object.fromEntries(model.tokens.map((t) => [t.path, leafValue(t)])), null, 2)}\n`;
}

// Tailwind section for a token, or null. Key = path minus the root (and a leading `duration`/`ease` after `motion`).
function tailwindSlot(t) {
  const [root, ...rest] = t.path.split('.');
  const drop = root === 'motion' && ['duration', 'ease'].includes(rest[0]) ? rest.slice(1) : rest;
  const flat = drop.join('-');
  if (t.$type === 'color') return ['colors', rest, true];
  if (t.$type === 'dimension' && root === 'space') return ['spacing', [flat]];
  if (t.$type === 'dimension' && root === 'radius') return ['borderRadius', [flat]];
  if (t.$type === 'fontFamily') return ['fontFamily', [rest.filter((s) => s !== 'family').join('-')]];
  if (t.$type === 'duration') return ['transitionDuration', [flat]];
  if (t.$type === 'cubicBezier') return ['transitionTimingFunction', [flat]];
  if (t.$type === 'shadow') return ['boxShadow', [flat]];
  if (t.$type === 'number' && ['z', 'zIndex', 'z-index'].includes(root)) return ['zIndex', [flat]];
  return null;
}

export function renderTailwind(model, prefix, { commonjs = false } = {}) {
  const sections = {};
  for (const t of model.tokens) {
    const slot = tailwindSlot(t);
    if (!slot || slot[1].length === 0 || slot[1][0] === '') continue;
    (sections[slot[0]] ??= []).push([slot[1], `var(${cssName(prefix, t.path)})`]);
  }
  const extend = Object.fromEntries(Object.entries(sections).map(([k, pairs]) => [k, nest(pairs)]));
  const body = JSON.stringify({ theme: { extend } }, null, 2);
  return `// ${HEADER}\n${commonjs ? 'module.exports = ' : 'export default '}${body};\n`;
}

const RENDERERS = {
  css: (m, p) => renderCss(m, p),
  scss: (m, p) => renderScss(m, p),
  js: (m) => renderJs(m),
  ts: (m) => renderJs(m, { ts: true }),
  json: (m) => renderJson(m),
  tailwind: (m, p, out) => renderTailwind(m, p, { commonjs: out.path.endsWith('.cjs') }),
};

// ---------- model ----------

function loadTheme(name, dir, baseTree, baseTokens, baseErrors, { siblings }) {
  const themeTree = loadTree(dir);
  const merged = resolveTokens(flatten(deepMerge(baseTree, themeTree)));
  const overridden = new Set(flatten(themeTree).map((t) => t.path));
  const known = new Set(baseTokens.map((t) => t.path));
  const tokens = merged.tokens.filter((t) => overridden.has(t.path));
  const errors = [
    // With sibling themes, a role the default theme lacks is reported by the parity check instead.
    ...(siblings ? [] : [...overridden].filter((p) => !known.has(p)).map((p) => `theme ${name}: overrides unknown token ${p}`)),
    ...merged.errors.filter((e) => !baseErrors.includes(e)).map((e) => `theme ${name}: ${e}`),
    ...validateTokens(tokens.filter((t) => known.has(t.path))).map((e) => `theme ${name}: ${e}`),
  ];
  return { theme: { name, tokens: tokens.filter((t) => known.has(t.path)) }, paths: overridden, errors };
}

/** Every theme must define the same paths as the default theme. */
function parityErrors(themes, defaultTheme) {
  const ref = themes.find((t) => t.theme.name === defaultTheme).paths;
  return themes.filter((t) => t.theme.name !== defaultTheme).flatMap(({ theme, paths }) => [
    ...[...ref].filter((p) => !paths.has(p)).map((p) => `theme ${theme.name}: missing role ${p} (defined in ${defaultTheme})`),
    ...[...paths].filter((p) => !ref.has(p)).map((p) => `theme ${theme.name}: extra role ${p} (not in ${defaultTheme})`),
  ]);
}

/**
 * Load default tokens and themes. Returns {model, errors}. Paths in config are relative to `root`.
 * With `tokens.defaultTheme`, themes are siblings: the default theme merges into the base (so `:root`)
 * and every theme must define the same paths. Without it, a theme only overrides base tokens.
 */
export function loadModel(config, root) {
  const at = (p) => path.resolve(root, p);
  const themeDirs = Object.entries(config.tokens.themes ?? {});
  const defaultTheme = config.tokens.defaultTheme;
  for (const [name, dir] of themeDirs) if (!fs.existsSync(at(dir))) throw new Error(`theme "${name}": folder ${dir} does not exist`);
  if (defaultTheme !== undefined && !themeDirs.some(([name]) => name === defaultTheme)) {
    return { model: { tokens: [], themes: [] }, errors: [`defaultTheme "${defaultTheme}" is not a theme (${themeDirs.map(([n]) => n).join(', ') || 'none'})`] };
  }
  const sourceTree = loadTree(at(config.tokens.source), { skip: [at(path.join(config.tokens.source, 'themes')), ...themeDirs.map(([, d]) => at(d))] });
  const defaultDir = themeDirs.find(([name]) => name === defaultTheme)?.[1];
  const baseTree = defaultDir ? deepMerge(sourceTree, loadTree(at(defaultDir))) : sourceTree;
  const base = resolveTokens(flatten(baseTree));
  const baseErrors = [...base.errors, ...validateTokens(base.tokens)];
  const themes = themeDirs.map(([name, dir]) => loadTheme(name, at(dir), baseTree, base.tokens, baseErrors, { siblings: defaultDir !== undefined }));
  return {
    model: { tokens: base.tokens, themes: themes.map((t) => t.theme) },
    errors: [...baseErrors, ...themes.flatMap((t) => t.errors), ...(defaultDir ? parityErrors(themes, defaultTheme) : [])],
  };
}

/** Render every configured output in memory (none when the tokens have errors). Returns {outputs: [{path, content}], errors, model}. */
export function buildOutputs(config, root) {
  const { model, errors } = loadModel(config, root);
  if (errors.length) return { outputs: [], errors, model };
  const outputs = (config.tokens.outputs ?? []).map((out) => ({ path: out.path, content: RENDERERS[out.format](model, config.prefix, out) }));
  return { outputs, errors, model };
}

// ---------- naming lint ----------

const HUES = ['red', 'orange', 'yellow', 'amber', 'green', 'teal', 'cyan', 'blue', 'indigo', 'purple', 'violet', 'pink', 'gray', 'grey', 'black', 'white'];
const APPEARANCE = ['light', 'lighter', 'dark', 'darker'];
const RAW_SEGMENT = /^(?:-?\d*\.?\d+(?:px|rem|em|ms|s)|#?[0-9a-f]{6})$/i;

/**
 * Naming rules (warnings, never failures):
 *  1. raw-value name: any segment that is a raw value (`13px`, `150ms`, `1f2937`).
 *  2. appearance name: a semantic token (its value is an alias) named after a hue or light/dark
 *     (`color.text.blue-light`). Semantic names say what a token is for, not how it looks.
 *  3. raw value in tier 2/3: a token under a `semantic` or `component` group whose value is not an alias.
 */
export function lintNames(tokens) {
  const warnings = [];
  for (const t of tokens) {
    const segments = t.path.split('.');
    const words = segments.flatMap((s) => s.split('-'));
    if (segments.some((s) => RAW_SEGMENT.test(s))) warnings.push(`${t.path}: name contains a raw value; name the step, not the value`);
    else if (t.aliasOf && words.some((w) => HUES.includes(w) || APPEARANCE.includes(w))) {
      warnings.push(`${t.path}: semantic token is named after its look; name its intent`);
    } else if (!t.aliasOf && ['semantic', 'component'].includes(segments[0])) {
      warnings.push(`${t.path}: raw value in the ${segments[0]} tier; alias a primitive token`);
    }
  }
  return warnings;
}

// ---------- typography: typefaces -> fonts -> text styles ----------

const isStack = (t) => t.$type === 'fontFamily' && !t.aliasOf;
const startsIn = (t, group) => t.path.split('.')[0] === group;

/** Error `typography.fallback-generic`: a font stack must end in a CSS generic family. Aliases are checked at their source. */
export function typographyErrors(tokens) {
  return tokens.filter(isStack).filter((t) => !GENERIC_FAMILIES.includes(lastFamily(t.resolved).toLowerCase())).map((t) =>
    `typography.fallback-generic ${t.path}: the stack ends in "${lastFamily(t.resolved)}"; end it with a generic family (${GENERIC_FAMILIES.join(', ')})`);
}

/**
 * Warnings for the chain. Components read text styles; a text style reads a font role; a font role aliases a typeface.
 *  1. a text style that aliases `typeface.*` directly;
 *  2. a `font.*` role that holds a raw stack instead of an alias;
 *  3. a family name in a `font.*` or text style token name (family names belong to `typeface.*`).
 */
export function lintTypography(tokens) {
  const ids = catalogIds();
  const warnings = [];
  for (const t of tokens) {
    const segments = t.path.split('.');
    const isFont = startsIn(t, FONT_GROUP);
    const isText = startsIn(t, TEXT_GROUP);
    if (isText && t.$type === 'fontFamily' && t.aliasOf?.startsWith(`${TYPEFACE_GROUP}.`)) {
      warnings.push(`${t.path}: text style aliases ${t.aliasOf} directly; alias ${FONT_GROUP}.<role> instead`);
    }
    if (isFont && isStack(t)) warnings.push(`${t.path}: font role holds a raw stack; alias a ${TYPEFACE_GROUP}.* token instead`);
    const named = (isFont || isText) && segments.find((s) => ids.includes(s));
    if (named) warnings.push(`${t.path}: name contains the family "${named}"; name the ${isFont ? `role (${ROLES.join(', ')})` : 'style by purpose'}`);
  }
  return warnings;
}

// ---------- check + CLI ----------

const readOrNull = (file) => (fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null);

/** A theme role reads the palette directly (heuristic: its alias target starts with `palette.`). Themes alias colors.*. */
export function lintThemes(themes) {
  return themes.flatMap((theme) => theme.tokens
    .filter((t) => t.aliasOf?.startsWith('palette.'))
    .map((t) => `theme ${theme.name}: role ${t.path} aliases the palette directly; alias colors.* instead`));
}

/** Validation errors, drifted output paths, naming warnings. */
export function checkProject(config, root) {
  const { outputs, errors, model } = buildOutputs(config, root);
  const drift = outputs.filter((o) => readOrNull(path.resolve(root, o.path)) !== o.content).map((o) => o.path);
  return {
    errors: [...errors, ...typographyErrors(model.tokens)],
    drift,
    warnings: [...lintNames(model.tokens), ...lintTypography(model.tokens), ...lintThemes(model.themes)],
  };
}

function readConfig(file) {
  if (!fs.existsSync(file)) throw new Error(`config not found: ${file}`);
  const config = JSON.parse(fs.readFileSync(file, 'utf8'));
  if (!config.prefix || !config.tokens?.source) throw new Error(`${file}: "prefix" and "tokens.source" are required`);
  for (const out of config.tokens.outputs ?? []) {
    if (!FORMATS.includes(out.format)) throw new Error(`${file}: unknown output format "${out.format}" (${FORMATS.join(', ')})`);
  }
  return config;
}

function build(config, root, io) {
  const { outputs, errors } = buildOutputs(config, root);
  if (errors.length) return (errors.forEach((e) => io.error(`error: ${e}`)), 1);
  for (const out of outputs) {
    const file = path.resolve(root, out.path);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, out.content);
    io.log(`wrote ${out.path}`);
  }
  return 0;
}

function check(config, root, io) {
  const { errors, drift, warnings } = checkProject(config, root);
  errors.forEach((e) => io.error(`error: ${e}`));
  warnings.forEach((w) => io.log(`warn: ${w}`));
  drift.forEach((p) => io.error(`drift: ${p} is out of date (run: tokens.mjs build)`));
  if (!errors.length && !drift.length) io.log(`tokens ok (${warnings.length} warning${warnings.length === 1 ? '' : 's'})`);
  return errors.length || drift.length ? 1 : 0;
}

const USAGE = 'Usage: tokens.mjs <build|check> [--config ./bauhaus.config.json]';

export function main(argv, io = console) {
  try {
    const { values, positionals } = parseArgs({ args: argv, allowPositionals: true, options: { config: { type: 'string', default: './bauhaus.config.json' } } });
    const command = positionals[0];
    if (!['build', 'check'].includes(command)) return (io.error(USAGE), 2);
    const file = path.resolve(values.config);
    const config = readConfig(file);
    const root = path.dirname(file);
    return command === 'build' ? build(config, root, io) : check(config, root, io);
  } catch (err) {
    io.error(`tokens: ${err.message}`);
    return 2;
  }
}

const invoked = process.argv[1] && fileURLToPath(import.meta.url) === fs.realpathSync(process.argv[1]);
if (invoked) process.exitCode = main(process.argv.slice(2));
